github.com:
    users:
        JoaoGabrielFer:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: JoaoGabrielFer
