#!/usr/bin/env bash

set -e

STATE_DIR="$HOME/.local/state/dot"
STATE_FILE="$HOME/.local/state/dot/installed_target"
TARGETS=( "arch-desktop" "arch-wsl" )

print_usage_exit() {
	echo -e "\033[33mUSAGE: \033[0m"
	echo "    $0 <command>"
	echo ""
	echo "commands:"
	echo "    help             -> output this message"
	echo "    install {target} -> install the desired configuration"
	echo "    targets          -> list all avaliable configurations"
	echo "    update           -> fetch the latest changes and updates the local environment"
	echo "    push             -> push the current config into the remote repository"
	exit 0
}

print_error() {
	echo -e "\033[31mERROR:\033[0m $1"
}

install_target() {
	echo -e "\033[32mInstalling...\033[0m"

	case $1 in
		arch-desktop)
			./install-arch-desktop.sh
			./install-shared.sh
			;;
		arch-wsl)
			./install-shared.sh
			;;
	esac
}

link_target() {
	echo -e "\033[32mCreating symlinks...\033[0m"

	case $1 in
		arch-desktop)
			./link-arch-desktop.sh
			./link-shared.sh
			;;
		arch-wsl)
			./link-shared.sh
			;;
	esac
}

get_target() {
    if [[ -f "$STATE_FILE" ]]; then
        # Extrai o valor
        local found_path=$(grep "^installed_target=" "$STATE_FILE" | cut -d'=' -f2-)
        
        if [[ -n "$found_path" ]]; then
            echo "$found_path"
            return 0
        fi
    fi
    return 1 
}

contains() {
    local busca="$1"
    shift 
    
    for item in "$@"; do
        [[ "$item" == "$busca" ]] && return 0 
    done
    
    return 1 
}

main(){
	if [[ $# -lt 1 ]]; then
		print_error "Missing command"
		print_usage_exit
	fi

	case $1 in
		help)
			print_usage_exit
			;;
		install)
			if  [[ $# -lt 2 ]] || ! contains "$2" "${TARGETS[@]}" ;then
				print_error "Missing or unknown target."
				print_usage_exit
			fi
			if [[ $(get_target) == "" ]]; then
				mkdir -p $STATE_DIR
				# install_target $2
				link_target $2
				echo -e "\033[32mDone!\033[0m"
				echo "installed_target=$2" > $STATE_FILE
			else
				echo -e "\033[33mWARNING:\033[0m Instalation detected."
				echo -en "Do you wish to reinstall? (\033[32mY\033[0m/\033[31mn\033[0m) "
				read input
				case $input in
					"" | "y")
						install_target $2
						link_target $2
						echo -e "\n\033[32mDone!\033[0m"
						rm $STATE_FILE
						echo "installed_target=$2" > $STATE_FILE
						;;
					*)
						exit 0
						;;
				esac
			fi
			;;
		targets)
			echo  "Targets: "
			echo -e "    \033[34march-desktop"
			echo -e "    arch-wsl\033[0m"
			;;
		update)
			if [[ $(get_target) == "" ]]; then
				print_error "Instalation not detected. Please install first."
				exit 1
			fi
			if [[ -d "$HOME/dotfiles/.git" ]]; then
				pushd $HOME/dotfiles/ 1>/dev/null
				echo -e "\033[32mDownloading latest changes...\033[0m"
				git fetch
				git pull origin main
				echo
				popd 1>/dev/null
			else
				print_error "Repository not found."
				exit 1
			fi

			link_target $(get_target)
			echo -e "\n\033[32mDone!\033[0m"
			;;
		push)
			if [[ -d "$HOME/dotfiles/.git" ]]; then
				pushd $HOME/dotfiles/ 1>/dev/null
				echo -e "\033[32mDownloading latest changes...\033[0m"
				git add .
				echo -e "\nInsira a mensagem de commit:"
				echo -en "\033[32m>> \033[0m"
				read msg
				git commit -m "$msg"
				git push origin main
				popd 1>/dev/null
			else
				print_error "Repository not found."
				exit 1
			fi
			;;
		*)
			print_error "Unknown command."
			print_usage_exit 
			;;
	esac
}

main $@
