require("modules.windowrules")
require("modules.monitor")
require("modules.env")
require("modules.autostart")
require("modules.aesthetic")
require("modules.binds")
require("modules.layout")
require("modules.misc")
require("modules.input")

